version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_FOLDER=/home/node/.n8n
      - HF_API_KEY=${HF_API_KEY}
      - SCAN_PATH=${SCAN_PATH:-/data/scan}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:3000/webhook}
    volumes:
      - ./n8n_workflows:/home/node/.n8n/workflows
      - ${SCAN_PATH:-./data/scan}:/data/scan
    restart: always

  security-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HF_API_KEY=${HF_API_KEY}
    volumes:
      - ${SCAN_PATH:-./data/scan}:/app/scan
    depends_on:
      - n8n 